
# POST http://localhost:30000/api/v1/laoapps_ewallet/user/sign_up HTTP/1.1
# Content-Type: application/json

# {
#     "username":"3",
#     "password":"3",
#     "email":"3",
#     "phonenumber":"3"
# }
POST http://localhost:4500 HTTP/1.1
Content-Type: application/json

{
    "object": "user",
    "method": "register",
    "data": {
        "name": "3",
        "phoneNumber": "3",
        "username": "3",
        "password": "3"
    }
}

###
POST http://localhost:4500 HTTP/1.1
Content-Type: application/json

{
    "object": "authorize",
    "method": "signHashByUuid",
    "data": {
        "token":"291b1120-60f0-11ec-a294-81fb2b588b1c",
        "service": "LAABWALLET",
        "hash": ""
    }
}





###
PUT  http://localhost:8888/admin/createUser HTTP/1.1
Content-Type: application/json
Headers: '9F58A83B7628211D6E739976A3E3A'
# BackendKey: 04573b1b-22f5-47f8-979c-fe4bc137a857

{ 
    "phonenumber":"1",
    "password":"1"
}


### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/pay HTTP/1.1
Content-Type: application/json

{
    "sender":"1",
    "receiver":"2",
    "content":"",
    "description":"",
    "reference":"",
    "limitBlock": "10",
    "amount":"100",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IjA0M2FiYzczYzFjNzUxZDRiN2I4M2RiYTE2NzQwNTJkN2ZiYTc4YjliNThjOTcxOGRmNjM5YWNiNjhmYWM1YWRiYjM0MmYwZjUwMmM3MjRmYTM3MDA3YzZiY2MwMTI4YjU1YmQ1YTBiNTc4YjAzYjlhODg3ZGMxODZkOTQ0MGE5MjkiLCJwaG9uZU51bWJlciI6IjEiLCJ1dWlkIjoiODQzN2RjNDAtNjE2NC0xMWVjLWEzOTYtMWIxNDM4MGMwOTQ4IiwiaXAiOiIxMjcuMC4wLjEiLCJtYWNoaW5lIjoid2luZG93cyIsIm90aGVyaW5mbyI6Imxhb2FwcC5jb20iLCJsb2NhdGlvbiI6InZpZW50aWFuZSJ9LCJpYXQiOjE2NDAwMTM0MjMsImV4cCI6MzYwMDAwMDE2NDAwMTM0MjR9.WoOygvCkP9ZvhH24q4peM26b1S3zL1fH1QhN1MDyzmw"

}





### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/total HTTP/1.
Content-Type: application/json

{
    "sender":"2",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}






### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/report_total_expend_value HTTP/1.1
Content-Type: application/json

{
    "sender":"1",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}





### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/total HTTP/1.1
Content-Type: application/json

{
    "sender": "2",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}





### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/report_rows HTTP/1.1
Content-Type: application/json

{
    "sender":"1",
    "page":"1",
    "limit":"5",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}






### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/report_history_income HTTP/1.1
Content-Type: application/json

{
    "sender":"2",
    "page":"1",
    "limit":"5"
}






### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/report_history_expend HTTP/1.1
Content-Type: application/json

{

    "sender":"2",
    "page":"1",
    "limit":"5"

}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/current_verify_hash_string HTTP/1.1
Content-Type: application/json

{
    "sender": "1",
    "hashM": "304402204e973353071147dba4ea976d7d7b909cd6d686ac13ab67c745a04ec763d1811702203d897f25e8e5b8677cbf3eee22edfbc79900a7324899e075b81ddd01f9e0cd93",
    "qrVerify":"false",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}




###
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/current_verify_hash_string_byQRCODE HTTP/1.1
Content-Type: application/json

{
    "sender": "1",
    "hashM": "30450221009d0bfcd8a3b9e11aa6f4aafa7bc4f58946731f16a287812b149293afd87c9cd9022008fd85916a7b07a6467d1631630a3bb966e85baf1a116c052602b6c2a68534b0",
    "qrVerify":"true",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}






### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/report_notification HTTP/1.1
Content-Type: application/json

{

    "sender":"issuer",
    "notification":"yes",
    "date": "2022-01-11",
    "page":"1",
    "limit":"5",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"

}





### 
POST http://localhost:30000/api/v1/laoapps_ewallet/wallet/read_notification HTTP/1.1
Content-Type: application/json

{

    "sender":"2",
    "notificationUuid":"304502207687e5702adee680117ff4338a48bef00dcc2fe44be846bc8fa65ccf0cb7a830022100f5625462643b43e5d5d78136c775e149a266df876a078b1a6a6b70b50eb0995b",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"

}








###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/issue HTTP/1.1
Content-Type: application/json

{
    "amount":"50000"
}






###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/pay HTTP/1.1
Content-Type: application/json

{
    "receiver":"1",
    "amount":"50000",
    "content":"",
    "description":"",
    "reference":"",
    "limitBlock":"10"
}






###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/total HTTP/1.1
Content-Type: application/json

{

}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/data HTTP/1.1
Content-Type: application/json

{

}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/total HTTP/1.1
Content-Type: application/json

{

}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/report_total_issued HTTP/1.1
Content-Type: application/json

{
    "page":"1",
    "limit":"5"
}






###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/report_history_expend HTTP/1.1
Content-Type: application/json

{
    "page":"1",
    "limit":"5"
}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/current_verify_hash_string HTTP/1.1
Content-Type: application/json

{
    "sender": "1",
    "hashM": "3046022100e57a3ef592820684361010f59a900a4252051aebe8477a6b355cf5c4871e4853022100b5b974b0a3748077246a160d3f3ddda0ad825f9b046c183c166a3e782797d94b",
    "qrVerify":"false",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}




###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/current_verify_hash_string_byQRCODE HTTP/1.1
Content-Type: application/json

{
    "sender": "1",
    "hashM": "3045022100c2132ffe3adf80e636c161355d6f4e03fe231299d6b4f296d00f25f01fd0f9a002203df5435544db0f0a09a7a79fc2a8d14fdfc3b3ce0aef4f7937d8526310d82dac",
    "qrVerify":"true",
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"
}







###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/report_notification HTTP/1.1
Content-Type: application/json

{

    "sender":"issuer",
    "notification":"no",
    "date": "2022-01-11",
    "page":"1",
    "limit":"5",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"

}





###
POST http://localhost:30000/api/v1/laoapps_ewallet/issuer/read_notification HTTP/1.1
Content-Type: application/json

{

    "sender":"issuer",
    "notificationUuid":"3045022100ba2b791c8654b9800c1641212024b90618837b047146c41d9210a152a35a532102202b3dd1d30510c3e149db772279fefcfc880eb0570ddaea16f861593007e10acf",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNpZ25hdHVyZSI6IiQyYSQxMCRXTFJvWmFvaXcyMHVjMm1OcVJBOFN1RTBmbk0xaFlpeVpZcXU2QUpKU05yMVh1bmhYUnhLbSIsInBob25lTnVtYmVyIjoiMSIsInV1aWQiOiIwNDhmMGFiMC01YjRmLTExZWMtOTI5Yi0zZmU3ZDQ0NmIyOTQiLCJpcCI6IjEyNy4wLjAuMSIsIm1hY2hpbmUiOiJ3aW5kb3dzIiwib3RoZXJpbmZvIjoibGFvYXBwLmNvbSIsImxvY2F0aW9uIjoidmllbnRpYW5lIn0sImlhdCI6MTYzOTMyNjYzMCwiZXhwIjozNjAwMDAwMTYzOTMyNjYzMH0.Xul4fVf9vqHhABUg8I2Y-OcagRB_9YmWiixqxjT5Neo"

}
















